echo "variables..."
export GIT_REPOSITORY="github.com/vinigomescunha/My-Deploy-Environment.git"
export DOCKER_IMG_TAG="vgcmdedockerimage:1.0"
export GIT_USERNAME="vinigomescunha"
# below https://github.com/settings/tokens :  "admin:repo_hook" and "repo"
export GIT_ACCESS_TOKEN="bd2ca74f30966b62efb3c0b363954b60579dc2d1"
export GIT_PROTOCOL="https://"
export PORT_SERVER="9000"
export HOST_SERVER="localhost"
