echo "variables..."
export GIT_REPOSITORY="github.com/vinigomescunha/My-Deploy-Environment.git"
export DOCKER_IMG_TAG="vgcmdedockerimage:1.0"
export GIT_USERNAME="vinigomescunha"
# below https://github.com/settings/tokens :  "admin:repo_hook" and "repo"
export GIT_ACCESS_TOKEN="d560c82d26c8d7f6b89b3938f0f1700fa57576db"
export GIT_PROTOCOL="https://"
export PORT_SERVER="9000"
export HOST_SERVER="localhost"
